# Streamlit secrets configuration
# This file should be kept private and not committed to version control

[general]
# Application secrets
app_secret_key = "premise-cv-dashboard-2024"
debug_mode = false

[database]
# Database configuration (if needed in the future)
# db_host = "localhost"
# db_port = 5432
# db_name = "premise_cv"
# db_username = "premise_user"
# db_password = "your_secure_password"

[api_keys]
# External API keys (if needed)
# openai_api_key = "your_openai_key"
# google_api_key = "your_google_key"

[performance]
# Performance monitoring settings
enable_performance_monitoring = true
max_memory_usage_gb = 8
max_cpu_usage_percent = 80

[video_processing]
# Video processing configuration
max_video_size_mb = 200
max_processing_time_minutes = 30
default_frame_skip = 1
enable_gpu_acceleration = true

[logging]
# Logging configuration
log_level = "INFO"
enable_file_logging = true
max_log_file_size_mb = 50